version: '3.8'

services:
  darknet:
    image: darknet-hankai2
    build: .
    container_name: darknet-container
    runtime: nvidia  
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - QT_XCB_GL_INTEGRATION=none  # Necesario para DarkMark
      - DISPLAY=${DISPLAY}  # Permitir GUI de DarkMark en la máquina host
    volumes:
      - ./data:/darknet/data  # Montar carpeta de imágenes/videos
      - /tmp/.X11-unix:/tmp/.X11-unix  # Permitir GUI en el contenedor
      - type: bind  # Solo montar los repositorios sin sobrescribir la compilación
        source: ./darknet
        target: /darknet
        consistency: delegated
      - type: bind
        source: ./darkhelp
        target: /darkhelp
        consistency: delegated
      - type: bind
        source: ./darkmark
        target: /darkmark
        consistency: delegated
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
